# Generated by Django 3.1.1 on 2020-10-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CollegeAllotmentApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='BIOMED',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='CMPN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='ETRX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='EXTC',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='INFT',
            field=models.IntegerField(default=0),
        ),
    ]
